In [1]:
# Import dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Import the dependencies.
import gmaps
import requests

In [21]:
# Import csv file
weather_vacy_df = pd.read_csv("weather_data/WeatherPy_vacation.csv")

In [22]:
weather_vacy_df.head(16)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,5,Castro,BR,63.63,['clear sky'],-24.79,-50.01,CHACARA BAILLY
1,7,Chuy,UY,64.35,['few clouds'],-33.70,-53.46,Nuevo Hotel Plaza
2,10,Itaituba,BR,73.35,['overcast clouds'],-4.28,-55.98,Hotel Campos
3,15,Acarau,BR,75.87,['overcast clouds'],-2.89,-40.12,castelo pizzaria
4,16,Cape Town,ZA,64.99,['few clouds'],-33.93,18.42,Southern Sun Waterfront Cape Town
5,19,Atar,MR,65.07,['clear sky'],20.52,-13.05,Oumou Elghoura
6,21,General Pico,AR,70.11,['clear sky'],-35.66,-63.76,Hotel Malargue
7,23,Busselton,AU,66.00,['few clouds'],-33.65,115.33,Observatory Guest House
8,30,Port Alfred,ZA,66.00,['overcast clouds'],-33.59,26.89,The Halyards Hotel
9,32,Saint-Philippe,RE,71.60,['broken clouds'],-21.36,55.77,"Chambres d'hôte ""La Trinité"""
10,35,Vaini,TO,73.40,['light rain'],-21.20,-175.20,Keleti Beach Resort
11,40,Hays,US,55.99,['overcast clouds'],30.05,-98.03,Sinya on Lone Man Creek
12,42,China,MX,73.35,['overcast clouds'],25.70,-99.23,Hotel Viajero
13,47,Monte Alegre,BR,73.53,['overcast clouds'],-2.01,-54.07,Hotel Shekinah
14,51,Grand Gaube,MU,73.00,['few clouds'],-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
15,58,Bredasdorp,ZA,62.60,['broken clouds'],-34.53,20.04,Bredasdorp Country Manor

In [23]:
len(weather_vacy_df)

200

In [33]:
weather_vacy_df1 = weather_vacy_df.loc[(weather_vacy_df["City"] == 'Galveston')]
weather_vacy_df2 = weather_vacy_df.loc[(weather_vacy_df["City"] == 'Hays')]
weather_vacy_df3 = weather_vacy_df.loc[(weather_vacy_df["City"] == 'Laredo')]
weather_vacy_df4 = weather_vacy_df.loc[(weather_vacy_df["City"] == 'China')]

In [79]:
weather_vacy_df3.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
125,352,Laredo,US,66.2,['overcast clouds'],27.51,-99.51,La Quinta Inn by Wyndham Laredo I-35

In [35]:
import gmaps
import gmaps.datasets
# Import the API key.
from config import g_key

In [36]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [89]:
# Add a map of the vacation spots and marker layer for each city.
# Latitude-longitude pairs
Galveston = (29.37, -94.97)  
Hays = (30.05, -98.03) 
Laredo = (27.51, -99.51)
China = (25.7, -99.23)
fig = gmaps.figure() 
galveston2china = gmaps.directions_layer(Galveston, China, waypoints=[Hays, Laredo], travel_mode = 'DRIVING')
fig.add_layer(galveston2china)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [102]:
preferred_city = weather_vacy_df1.copy()
preferred_city = preferred_city.append(weather_vacy_df2)
preferred_city = preferred_city.append(weather_vacy_df3)
preferred_city = preferred_city.append(weather_vacy_df4)
preferred_city = preferred_city.reset_index()
preferred_city = preferred_city.drop('index', 1)
preferred_city = preferred_city.drop('City_ID', 1)
preferred_city

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Galveston,US,72.00,['light rain'],29.37,-94.97,Comfort Inn & Suites Texas City
1,Hays,US,55.99,['overcast clouds'],30.05,-98.03,Sinya on Lone Man Creek
2,Laredo,US,66.20,['overcast clouds'],27.51,-99.51,La Quinta Inn by Wyndham Laredo I-35
3,China,MX,73.35,['overcast clouds'],25.70,-99.23,Hotel Viajero

In [107]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in preferred_city.iterrows()]

In [108]:
# Add a map of the vacation spots and marker layer for each city and a pop-up marker for each city.
locations = preferred_city[["Lat", "Lng"]]
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))